#!/bin/bash

# 째깍홈티 GitHub & Vercel 배포 스크립트
# 사용법: 이 파일을 참고하여 터미널에서 명령어 실행

echo "=== 째깍홈티 배포 가이드 ==="
echo ""
echo "📝 Step 1: GitHub 저장소 연결"
echo ""
echo "먼저 GitHub에서 저장소를 만드세요:"
echo "https://github.com/new"
echo ""
echo "그 다음 아래 명령어를 실행하세요:"
echo "(YOUR_USERNAME을 실제 GitHub 사용자명으로 변경)"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/jjaekkak-homti-landing.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "---"
echo ""
echo "📝 Step 2: Vercel 배포"
echo ""
echo "방법 A: Vercel 웹사이트 (추천)"
echo "1. https://vercel.com 접속"
echo "2. GitHub 계정으로 로그인"
echo "3. 'Add New...' → 'Project'"
echo "4. GitHub 저장소 선택: jjaekkak-homti-landing"
echo "5. 'Import' 클릭"
echo "6. 설정 그대로 두고 'Deploy' 클릭"
echo ""
echo "방법 B: Vercel CLI"
echo "npm install -g vercel"
echo "vercel login"
echo "vercel --prod"
echo ""
echo "---"
echo ""
echo "✅ 배포 완료 후 확인사항:"
echo "1. 배포된 URL 접속"
echo "2. 부모 신청서 테스트"
echo "3. Google Sheets 데이터 확인"
echo "4. 치료사 신청서 테스트"
echo ""
